# # this one is used as a mock API
# # backend/main.py
# from fastapi import FastAPI
# from fastapi.middleware.cors import CORSMiddleware
# from pydantic import BaseModel
# from typing import List, Optional

# app = FastAPI()

# # --- CORS: allow frontend (browser) to call this API locally ---
# app.add_middleware(
#     CORSMiddleware,
#     allow_origins=["*"],  # 开发阶段先放开，之后可以改成具体域名
#     allow_credentials=True,
#     allow_methods=["*"],
#     allow_headers=["*"],
# )

# # ---------- Data models ----------

# class ChatRequest(BaseModel):
#     message: str
#     language: str = "en"
#     region: str = "EU"
#     tone: str = "formal"

# class ChatResponse(BaseModel):
#     reply: str


# class DocumentRequest(BaseModel):
#     document_type: str
#     currency: str
#     seller_name: str
#     buyer_name: str
#     product: str
#     quantity: int
#     unit_price: float
#     incoterm: Optional[str] = None
#     payment_term: Optional[str] = None
#     extra_notes: Optional[str] = None

# class DocumentResponse(BaseModel):
#     document_text: str


# class RiskRequest(BaseModel):
#     message: str
#     country: Optional[str] = None
#     transaction_type: Optional[str] = None

# class RiskResponse(BaseModel):
#     risks: List[str]
#     explanation: str


# # ---------- Mock endpoints ----------

# @app.post("/api/chat", response_model=ChatResponse)
# async def mock_chat(req: ChatRequest):
#     """
#     Mock business communication endpoint.
#     Returns a fake but realistic email reply.
#     """
#     reply = f"""Dear Customer,

# Thank you for your message:

# "{req.message}"

# This is a MOCK response from the backend (no real LLM yet).
# In the future, this endpoint will generate a culturally appropriate business email
# for region: {req.region}, tone: {req.tone}, language: {req.language}.

# Best regards,
# AI Trade Assistant (Mock)
# """
#     return ChatResponse(reply=reply)


# @app.post("/api/document", response_model=DocumentResponse)
# async def mock_document(req: DocumentRequest):
#     """
#     Mock document generation endpoint.
#     Returns a simple text version of a Proforma Invoice / Quotation, etc.
#     """
#     total = req.quantity * req.unit_price

#     doc = f"""DOCUMENT TYPE: {req.document_type.upper()}

# Seller: {req.seller_name}
# Buyer: {req.buyer_name}

# Product: {req.product}
# Quantity: {req.quantity}
# Unit price: {req.unit_price:.2f} {req.currency}
# Total amount: {total:.2f} {req.currency}

# Incoterm: {req.incoterm or "N/A"}
# Payment term: {req.payment_term or "N/A"}

# Additional notes:
# {req.extra_notes or "N/A"}

# -- This is a MOCK document generated by the backend.
# -- Later this will be replaced by a proper document template + LLM / template engine.
# """
#     return DocumentResponse(document_text=doc)


# @app.post("/api/risk", response_model=RiskResponse)
# async def mock_risk(req: RiskRequest):
#     """
#     Mock risk analysis endpoint.
#     For now it always returns a placeholder risk label.
#     """
#     risks = ["not_implemented"]
#     explanation = (
#         "This is a placeholder response. The risk analysis module has not been "
#         "implemented yet. In the future, this endpoint will analyse the message "
#         "for payment risks, fraud indicators, and compliance issues."
#     )
#     return RiskResponse(risks=risks, explanation=explanation)
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.routers.com_router import router as com_router

app = FastAPI(
    title="AI Trade Assistant Backend",
    description="Backend for trade communication, document generation, and risk analysis.",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ⭐ 这里 prefix="/api"
app.include_router(com_router, prefix="/api", tags=["communication"])


@app.get("/")
async def root():
    return {"status": "ok", "message": "Backend is running"}
